#include <codegen.hpp>
#include <iostream>

using namespace std;

Codegen::Codegen(Analyzer &analyzer, ostream &os) : analyzer(analyzer), os(os)
{
    os << "\t; Generated by ZDK C Compiler\n\n";
}

CXChildVisitResult Codegen::visit(CXCursor cursor, CXCursor parent)
{
    CXCursorKind kind = clang_getCursorKind(cursor);

    switch (kind)
    {
    case CXCursor_FunctionDecl:
    {
        CXString name = clang_getCursorSpelling(cursor);
        os << "\t.global " << clang_getCString(name) << "\n";
        clang_disposeString(name);
        return CXChildVisit_Recurse;
    }
    case CXCursor_CompoundStmt:
        return visitCompoundStmt(cursor, parent);
    }

    return CXChildVisit_Continue;
}

CXChildVisitResult Codegen::visitCompoundStmt(CXCursor cursor, CXCursor parent)
{
    if (clang_getCursorKind(parent) == CXCursor_FunctionDecl)
    {
        CXString name = clang_getCursorSpelling(parent);
        os << "\t.type " << clang_getCString(name) << ", @function\n";
        os << clang_getCString(name) << ":\n";
        clang_disposeString(name);

        // TODO: Compile function body
        os << "\tret\n\n";
    }
    return CXChildVisit_Continue;
}
