#include <codegen.hpp>
#include <iostream>

using namespace std;

Codegen::Codegen(Analyzer &analyzer, ostream &os) : analyzer(analyzer), os(os)
{
    os << "\t; Generated by ZDK C Compiler\n\n";
}

CXChildVisitResult Codegen::visit(CXCursor cursor, CXCursor parent)
{
    CXCursorKind kind = clang_getCursorKind(cursor);

    switch (kind)
    {
    case CXCursor_FunctionDecl:
    {
        CXString name = clang_getCursorSpelling(cursor);
        os << "\t.global " << clang_getCString(name) << "\n";
        os << "\t.type " << clang_getCString(name) << ", @function\n";
        os << clang_getCString(name) << ":\n";
        clang_disposeString(name);
        
        // TODO: Implement function body
        os << "\tret\n";

        os << "\n";
        break;
    }
    }

    return CXChildVisit_Recurse;
}
