#include "target.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Z80-specific data */
struct Z80Data {
  int stack_offset;
  int temp_count;
  int label_count;
};

/* Z80 codegen implementations */

static void z80_gen_function(struct Codegen *cg, struct ASTNode *func) {
  struct ASTNode *body;
  
  if (!func || !cg->output) {
    return;
  }
  
  /* Function prologue */
  fprintf(cg->output, "\t; Function prologue\n");
  fprintf(cg->output, "\tpush ix\n");
  fprintf(cg->output, "\tld ix, 0\n");
  fprintf(cg->output, "\tadd ix, sp\n");
  
  /* Generate function body */
  body = func->u.ext.body;
  if (body && cg->gen_statement) {
    cg->gen_statement(cg, body);
  }
  
  /* Function epilogue */
  fprintf(cg->output, "\t; Function epilogue\n");
  fprintf(cg->output, "\tld sp, ix\n");
  fprintf(cg->output, "\tpop ix\n");
  fprintf(cg->output, "\tret\n");
}

static void z80_gen_statement(struct Codegen *cg, struct ASTNode *stmt) {
  struct ASTList *list;
  
  if (!stmt || !cg->output) {
    return;
  }
  
  switch (stmt->u.stmt.kind) {
    case STMT_COMPOUND:
      /* Generate each statement in the compound */
      for (list = stmt->u.stmt.stmts; list; list = list->next) {
        if (list->node && cg->gen_statement) {
          cg->gen_statement(cg, list->node);
        }
      }
      break;
      
    case STMT_RETURN:
      /* Generate the return expression */
      if (stmt->u.stmt.expr && cg->gen_expression) {
        cg->gen_expression(cg, stmt->u.stmt.expr);
      }
      /* Result is already in HL for i16 returns */
      break;
      
    case STMT_EXPR:
      /* Generate expression statement */
      if (stmt->u.stmt.expr && cg->gen_expression) {
        cg->gen_expression(cg, stmt->u.stmt.expr);
      }
      break;
      
    default:
      fprintf(cg->output, "\t; TODO: statement kind %d\n", stmt->u.stmt.kind);
      break;
  }
}

static void z80_gen_expression(struct Codegen *cg, struct ASTNode *expr) {
  if (!expr || !cg->output) {
    return;
  }
  
  switch (expr->u.expr.kind) {
    case EXPR_CONST:
      /* Load constant into HL (i16 for Z80) */
      fprintf(cg->output, "\tld hl, %s\n", expr->u.expr.const_tok.lexeme);
      break;
      
    default:
      fprintf(cg->output, "\t; TODO: expression kind %d\n", expr->u.expr.kind);
      break;
  }
}

/* Z80 target implementations */

static void z80_init(struct Codegen *cg) {
  struct Z80Data *data;
  data = (struct Z80Data *)malloc(sizeof(struct Z80Data));
  if (!data) {
    fprintf(stderr, "Failed to allocate Z80 target data\n");
    return;
  }
  data->stack_offset = 0;
  data->temp_count = 0;
  data->label_count = 0;
  cg->target_data = data;
  
  if (cg->output) {
    fprintf(cg->output, "; Z80 assembly output\n");
    fprintf(cg->output, "; Generated by zdk compiler\n");
    fprintf(cg->output, "; Target: Z80 (GNU binutils)\n\n");
    fprintf(cg->output, "\t.text\n\n");
  }
}

static void z80_finalize(struct Codegen *cg) {
  if (cg->target_data) {
    free(cg->target_data);
    cg->target_data = NULL;
  }
}

static int z80_invoke_assembler(struct Codegen *cg, const char *asm_file, const char *obj_file) {
  char cmd[1024];
  int ret;
  
  /* Use GNU binutils assembler for Z80 */
  sprintf(cmd, "z80-unknown-none-elf-as -o '%s' '%s'", obj_file, asm_file);
  ret = system(cmd);
  
  if (ret != 0) {
    fprintf(stderr, "Z80 assembler failed with exit code %d\n", ret);
    fprintf(stderr, "Command: %s\n", cmd);
    return 0;
  }
  
  return 1;
}

static int z80_invoke_linker(struct Codegen *cg, const char **obj_files, int num_objs, const char *out_file) {
  char cmd[2048];
  int i;
  int pos;
  int ret;
  
  /* Use GNU binutils linker for Z80 */
  sprintf(cmd, "z80-unknown-none-elf-ld -o '%s'", out_file);
  pos = strlen(cmd);
  
  for (i = 0; i < num_objs; i++) {
    sprintf(cmd + pos, " '%s'", obj_files[i]);
    pos = strlen(cmd);
  }
  
  ret = system(cmd);
  if (ret != 0) {
    fprintf(stderr, "Z80 linker failed with exit code %d\n", ret);
    fprintf(stderr, "Command: %s\n", cmd);
    return 0;
  }
  
  return 1;
}

static void z80_init_codegen(struct Codegen *cg) {
  /* Initialize with defaults first */
  codegen_init_defaults(cg);
  
  /* Override with Z80-specific implementations */
  cg->gen_function = z80_gen_function;
  cg->gen_statement = z80_gen_statement;
  cg->gen_expression = z80_gen_expression;
  
  /* Keep default implementation for gen_symbol */
}

/* Z80 target definition */
struct Target target_z80 = {
  "z80",
  "Zilog Z80 8-bit processor",
  "z80-unknown-none-elf-",
  
  z80_init,
  z80_finalize,
  
  z80_invoke_assembler,
  z80_invoke_linker,
  
  z80_init_codegen
};
