site_name: ZDK Documentation
site_url: https://atirut-w.github.io/zdk

repo_url: https://github.com/atirut-w/zdk/
repo_name: atirut-w/zdk
edit_uri: edit/main/docs/

nav:
  - 'index.md'
  - Development:
    - 'development/compiler-debugging.md'
  - ABI:
    - 'abi/calling-convention.md'

theme:
  name: material

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.tracking

  palette:
    - media: "(prefers-color-scheme)"
    - media: "(prefers-color-scheme: light)"
      scheme: "default"
      primary: "blue grey"
      accent: "grey"
    - media: "(prefers-color-scheme: dark)"
      scheme: "slate"
      primary: "black"
      accent: "grey"

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
