site_name: ZDK Documentation
site_url: https://atirut-w.github.io/zdk

repo_url: https://github.com/atirut-w/zdk/
repo_name: atirut-w/zdk
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
    - media: "(prefers-color-scheme: light)"
      scheme: "default"
      primary: "blue grey"
      accent: "grey"
    - media: "(prefers-color-scheme: dark)"
      scheme: "slate"
      primary: "black"
      accent: "grey"

markdown_extensions:
  - admonition
  - pymdownx.superfences
