#include "codegen.hpp"
#include "linear_scan_allocator.hpp"
#include "liveness_analyzer.hpp"
#include "z80.hpp"
#include <any>
#include <cassert>
#include <cstdio>
#include <iostream>
#include <llvm/IR/Constants.h>
#include <llvm/IR/Instruction.h>
#include <llvm/IR/Instructions.h>
#include <llvm/IR/Module.h>
#include <llvm/Support/raw_ostream.h>
#include <vector>

using namespace std;
using namespace llvm;
using namespace Z80;

Codegen::Codegen(ostream &os) : os(os) {
  os << "\t; Generated by ZDK IR compiler\n\n";
}

std::any Codegen::visit_module(Module &module) {
  this->module = &module;

  for (auto &func : module) {
    if (func.isDeclaration())
      continue;
    visit_function(func);
  }

  return {};
}

void Codegen::compute_offsets(Function &func) {
  for (auto &block : func) {
    for (auto &inst : block) {
      if (auto *alloca = dyn_cast<AllocaInst>(&inst)) {
        ctx.stack_offsets[alloca] = ctx.stack_size;
        ctx.stack_size += module->getDataLayout().getTypeAllocSize(
            alloca->getAllocatedType());
      } else if (!inst.getType()->isVoidTy()) {
        ctx.stack_offsets[&inst] = ctx.stack_size;
        ctx.stack_size +=
            module->getDataLayout().getTypeAllocSize(inst.getType());
      }
    }
  }

  if (ctx.stack_size > 128) {
    throw runtime_error("too many locals");
  }

  // cout << "Stack layout for " << func.getName().str() << ":\n";
  // for (auto [val, offset] : ctx.stack_offsets) {
  //   printf("  %p: %d\n", val, offset);
  // }
}

void Codegen::write_instruction(Instruction &inst) {
  string str;
  raw_string_ostream rso(str);
  inst.print(rso);
  os << "\t; " << rso.str() << "\n";
}

std::any Codegen::visit_function(Function &func) {
  os << "\t.global " << func.getName().str() << "\n";
  os << "\t.type " << func.getName().str() << ", @function\n";
  os << func.getName().str() << ":\n";
  ctx = {};

  LivenessAnalyzer analyzer;
  ctx.intervals = analyzer.compute_intervals(func);

  LinearScanAllocator allocator(module);
  allocator.allocate(ctx.intervals);
  compute_offsets(func);

  if (ctx.stack_size) {
    os << "\t; Allocate stack for " << ctx.stack_offsets.size() << " locals\n";
    os << "\tpush ix\n";
    os << "\tld ix, 0\n";
    os << "\tadd ix, sp\n";

    os << "\tld hl, -" << ctx.stack_size << "\n";
    os << "\tadd hl, sp\n";
  }

  for (auto &block : func) {
    visit_block(block);
  }

  return {};
}

std::any Codegen::visit_instruction(Instruction &inst) {
  write_instruction(inst);

  switch (inst.getOpcode()) {
  case Instruction::Ret:
    visit_return(cast<ReturnInst>(&inst));
  }

  return {};
}

void Codegen::visit_return(ReturnInst *inst) {
  if (ctx.stack_size) {
    os << "\t; Deallocate stack\n";
    os << "\tld sp, ix\n";
    os << "\tpop ix\n";
  }
  os << "\tret\n";
}
