#include "codegen.hpp"
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <iostream>
#include <llvm/IR/Constants.h>
#include <llvm/IR/Instructions.h>
#include <llvm/IR/Module.h>
#include <llvm/Support/raw_ostream.h>
#include <stdexcept>
#include <string>
#include <vector>

using namespace std;
using namespace llvm;

vector<char> r8_order = {'l', 'h', 'e', 'd'};
vector<string> r16_order = {"hl", "de"};

Codegen::Codegen(ostream &os, Module *module) : os(os), module(module) {
  os << "\t; Generated by ZDK IR compiler\n\n";
}

void Codegen::load(Value *value) {
  if (auto *const_int = dyn_cast<ConstantInt>(value)) {
    uint64_t size =
        module->getDataLayout().getTypeAllocSize(const_int->getType());

    if (size == 1) {
      os << "\tld a, " << const_int->getZExtValue() << "\n";
    } else if (size <= 4) {
      for (size_t i = 0; i < size / 2; i++) {
        os << "\tld " << r16_order[i] << ", "
           << ((const_int->getZExtValue() >> (i * 16)) & 0xffff) << "\n";
      }
    } else {
      throw runtime_error("Unsupported constant size");
    }
  } else if (auto *load = dyn_cast<LoadInst>(value)) {
    if (auto *alloc = dyn_cast<AllocaInst>(load->getPointerOperand())) {
      uint64_t size = module->getDataLayout().getTypeAllocSize(load->getType());
      if (size == 1) {
        os << "\tld a, (iy+" << ctx.locals[alloc] << ")\n";
      } else if (size <= 4) {
        for (size_t i = 0; i < size; i++) {
          os << "\tld " << r8_order[i] << ", (iy+" << ctx.locals[alloc] + i
             << ")\n";
        }
      } else {
        throw runtime_error("Unsupported load size");
      }
    } else {
      throw runtime_error("Unsupported load");
    }
  } else {
    throw runtime_error("Unsupported value");
  }
}

void Codegen::pregen_function(Function &func) {
  ctx = {};

  for (auto &block : func) {
    for (auto &inst : block) {
      if (auto *alloc = dyn_cast<AllocaInst>(&inst)) {
        ctx.locals[alloc] = ctx.stack_size;

        Type *type = alloc->getAllocatedType();
        ctx.stack_size += module->getDataLayout().getTypeAllocSize(type);
      }
    }
  }
}

void Codegen::write_instruction(Instruction &inst) {
  string str;
  raw_string_ostream rso(str);
  inst.print(rso);
  os << "\t; " << rso.str() << "\n";
}

void Codegen::generate_function(Function &func) {
  os << "\t.global " << func.getName().str() << "\n";
  os << "\t.type " << func.getName().str() << ", @function\n";
  os << func.getName().str() << ":\n";
  ctx = {};

  pregen_function(func);
  if (ctx.stack_size) {
    os << "\tpush iy\n";
    os << "\tpush ix\n";

    os << "\tld ix, 0\n";
    os << "\tadd ix, sp\n";
    os << "\tld iy, -" << ctx.stack_size << "\n";
    os << "\tadd iy, sp\n";
    os << "\tld sp, iy\n";
  }

  for (auto &block : func) {
    for (auto &inst : block) {
      write_instruction(inst);
      if (auto *alloc = dyn_cast<AllocaInst>(&inst)) {
        os << "\t;   (offset " << ctx.locals[alloc] << ")\n";
      } else if (auto *ret = dyn_cast<ReturnInst>(&inst)) {
        generate_return(ret);
      } else if (auto *load = dyn_cast<LoadInst>(&inst)) {
        ctx.locals[load] = ctx.locals[load->getPointerOperand()];
        os << "\t;   (aliased to offset " << ctx.locals[load] << ")\n";
      } else if (auto *store = dyn_cast<StoreInst>(&inst)) {
        generate_store(store);
      }
    }
  }

  os << "\n\n";
}

void Codegen::generate_epilogue() {
  if (ctx.stack_size) {
    os << "\tld sp, ix\n";
    os << "\tpop ix\n";
    os << "\tpop iy\n";
  }
}

void Codegen::generate_store(StoreInst *store) {
  Value *ptr = store->getPointerOperand();
  Value *val = store->getValueOperand();
  Type *type = val->getType();
  uint64_t size = module->getDataLayout().getTypeAllocSize(type);

  load(val);
  if (auto *alloc = dyn_cast<AllocaInst>(ptr)) {
    if (size == 1) {
      os << "\tld (iy+" << ctx.locals[alloc] << "), a\n";
    } else if (size <= 4) {
      for (size_t i = 0; i < size; i++) {
        os << "\tld (iy+" << ctx.locals[alloc] + i << "), " << r8_order[i]
           << "\n";
      }
    } else {
      throw runtime_error("Unsupported store size");
    }
  } else {
    throw runtime_error("Unsupported store");
  }
}

void Codegen::generate_return(ReturnInst *ret) {
  if (auto *val = ret->getReturnValue()) {
    load(val);
  }
  generate_epilogue();
  os << "\tret\n";
}

void Codegen::generate() {
  for (auto &func : module->functions()) {
    if (func.isDeclaration()) {
      continue;
    }
    generate_function(func);
  }
}
