#include <compiler.hpp>

using namespace std;

Compiler::Compiler(ModuleInfo &module_info, ostream &output) : module_info(module_info), os(output)
{
    os << "\t; Generated by ZDK IR Compiler\n\n";
}
