#include "types.hpp"
#include <cctype>
#include <codegen.hpp>
#include <iostream>
#include <string>

using namespace std;
using namespace antlr4;

vector<PrimitiveLayout> primitive_layouts = {
    {
        {},
        {}
    },
    {
            
        {'a'},
        {}
    },
    {
        {'l', 'h'},
        {"hl"}
    },
    {
        {'l', 'h'},
        {"hl"}
    }
};

CodeGen::CodeGen(Module &program_meta, std::ostream &output) : program_meta(program_meta), output(output)
{
    output << "\t; Generated by ZDK C Compiler\n\n";
}

void CodeGen::teardown_frame()
{
    // TODO: clause for arguments
    if (!current_function->locals.empty() || false)
    {
        output << "\tld sp, ix\n";
        output << "\tpop ix\n";
        if (!current_function->locals.empty())
        {
            output << "\tpop iy\n";
        }
    }
}

any CodeGen::visitFunctionDefinition(CParser::FunctionDefinitionContext *ctx)
{
    string name = ctx->declarator()->directDeclarator()->directDeclarator()->Identifier()->getText();
    current_function = &program_meta.functions[name];

    output << "\t.global " << name << "\n";
    output << "\t.type " << name << ", @function\n";
    output << name << ":\n";

    // TODO: clause for arguments
    if (!current_function->locals.empty() || false)
    {
        if (!current_function->locals.empty())
        {
            output << "\tpush iy\n";
        }
        output << "\tpush ix\n";
        output << "\tld ix, 0\n";
        output << "\tadd ix, sp\n";

        if (!current_function->locals.empty())
        {
            int alloc_size = 0;
            for (auto &local : current_function->locals)
            {
                if (auto *primitive = dynamic_cast<PrimitiveType *>(local.second.get()))
                {
                    alloc_size += primitive_layouts[primitive->kind].registers.size();
                }
                else
                {
                    throw runtime_error("unsupported local type");
                }
            }

            output << "\tld iy, " << -alloc_size << "\n";
            output << "\tadd iy, sp\n";
            output << "\tld sp, iy\n";
        }
    }

    if (auto block_itemlist_ctx = ctx->compoundStatement()->blockItemList())
    {
        for (auto block_item_ctx : block_itemlist_ctx->blockItem())
        {
            visit(block_item_ctx);
        }
    }

    if (!current_function->has_trailing_return)
    {
        teardown_frame();
        output << "\tret\n";
    }

    return any();
}

any CodeGen::visitJumpStatement(CParser::JumpStatementContext *ctx)
{
    if (ctx->Return())
    {
        if (ctx->expression())
        {
            visit(ctx->expression());
        }
        teardown_frame();
        output << "\tret\n";
    }
    else
    {
        throw runtime_error("unsupported jump statement");
    }

    return any();
}
