#include "include/backend/asm_printer.hpp"
#include "include/backend/allocator.hpp"
#include <algorithm>
#include <cstdlib>
#include <iostream>
#include <llvm/IR/BasicBlock.h>
#include <llvm/IR/Constants.h>
#include <llvm/IR/Instruction.h>
#include <llvm/IR/Instructions.h>
#include <llvm/IR/Type.h>
#include <llvm/Support/TypeSize.h>
#include <llvm/Support/raw_ostream.h>
#include <string>

using namespace std;
using namespace llvm;

map<int, string> register_names = {
    {Allocator::R8_A, "a"},        {Allocator::R8_B, "b"},        {Allocator::R8_C, "c"},    {Allocator::R8_D, "d"},
    {Allocator::R8_E, "e"},        {Allocator::R8_H, "h"},        {Allocator::R8_L, "l"},

    {Allocator::R16_BC, "bc"},     {Allocator::R16_DE, "de"},     {Allocator::R16_HL, "hl"},

    {Allocator::R32_BCDE, "bcde"}, {Allocator::R32_DEHL, "dehl"},
};

void AsmPrinter::generate_prologue() {
  int offset = 0;
  int blocknum = 0;

  for (auto &block : *fctx.current) {
    fctx.blocknums[&block] = blocknum++;

    for (auto &instruction : block) {
      if (auto alloca = dyn_cast<AllocaInst>(&instruction)) {
        Type *type = alloca->getAllocatedType();
        TypeSize size = module.getDataLayout().getTypeAllocSize(type);

        offset -= size;
        fctx.offsets[&instruction] = offset + 1;
      }
    }
  }

  for (auto &[value, alloc] : fctx.allocation) {
    if (alloc.spilled) {
      Type *type = value->getType();
      TypeSize size = module.getDataLayout().getTypeAllocSize(type);

      offset -= size;
      fctx.offsets[value] = offset + 1;
    }
  }

  if (offset < 0) {
    os << "\tpush ix\n";
    os << "\tld ix, 0\n";
    os << "\tadd ix, sp\n";

    os << "\tld hl, " << offset << "\n";
    os << "\tadd hl, sp\n";
    os << "\tld sp, hl\n";
  }
}

string AsmPrinter::get_ix(int base, int offset) {
  if (base + offset <= 0) {
    return "(ix-" + to_string(-(base + offset)) + ")";
  } else {
    return "(ix+" + to_string(base + offset) + ")";
  }
}

string AsmPrinter::get_label(const BasicBlock *block) {
  string label = to_string(fctx.blocknums[block]);
  if (fctx.blocknums[block] < fctx.blocknums[fctx.block]) {
    label += "b";
  } else {
    label += "f";
  }
  return label;
}

void AsmPrinter::print() {
  os << "\t; Generated by ZDK C Compiler\n\n";

  for (auto &function : module) {
    string name = function.getName().str();
    fctx = {};
    fctx.current = &function;

    Allocator allocator(module);
    allocator.run(function);
    fctx.allocation = allocator.allocation;

    os << "\t.global " << name << "\n";
    os << name << ":\n";
    generate_prologue();

    int ninst = 0;
    for (auto &block : function) {
      fctx.block = &block;
      os << fctx.blocknums[&block] << ":\n";
      for (auto &instruction : block) {
        string comment = "; ";
        raw_string_ostream rso(comment);
        instruction.print(rso);
        os << comment << "\n";

        // Ignore unused instructions
        if (!instruction.getType()->isVoidTy() && instruction.getNumUses() == 0) {
          os << "\t; (UNUSED)\n";
          continue;
        }
        
        // print_instruction(&instruction);
        ninst++;
      }
    }
  }
}

// void AsmPrinter::print_instruction(const Instruction *instruction) {
//   switch (instruction->getOpcode()) {
//   default:
//     outs() << *instruction << "\n";
//     // throw runtime_error("unhandled instruction");
//     cerr << "unhandled opcode: " << instruction->getOpcode() << "\n";
//     break;

//   // Terminator instructions :robot:
//   case Instruction::Ret:
//     print_return(cast<ReturnInst>(instruction));
//     break;
//   case Instruction::Br:
//     print_br(cast<BranchInst>(instruction));
//     break;

//   // Binary instructions
//   case Instruction::Add:
//     print_add(cast<BinaryOperator>(instruction));
//     break;
//   case Instruction::Sub:
//     print_sub(cast<BinaryOperator>(instruction));
//     break;
//   case Instruction::Xor:
//     print_xor(cast<BinaryOperator>(instruction));
//     break;

//   // Memory instructions
//   case Instruction::Alloca:
//     break;
//   case Instruction::Load:
//     print_load(cast<LoadInst>(instruction));
//     break;
//   case Instruction::Store:
//     print_store(cast<StoreInst>(instruction));
//     break;

//   // Cast instructions
//   case Instruction::ZExt:
//     print_zext(cast<ZExtInst>(instruction));
//     break;

//   // Other instructions
//   case Instruction::ICmp:
//     print_icmp(cast<ICmpInst>(instruction));
//     break;
//   case Instruction::PHI:
//     break;
//   }
// }
