#pragma once
#include "parser.hpp"
#include <ostream>

class Codegen
{
    std::ostream &os;

public:
    Codegen(std::ostream &os) : os(os)
    {
        os << "\t; Generated by ZDK C Compiler\n\n\n";
    }

    void visit(const ASTNode *node);
};
