set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR z80)
set(CMAKE_LINKER z80-elf-ld)

set(CMAKE_ASM_COMPILER z80-elf-as)
set(CMAKE_ASM_COMPILE_OBJECT "<CMAKE_ASM_COMPILER> <FLAGS> -o <OBJECT> <SOURCE>")

set(CMAKE_C_COMPILER zdk-sdcc)
set(CMAKE_C_COMPILER_WORKS 1)
