name: "Deploy docs to GitHub Pages"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: atirut-w/mkdocs-deploy@master
        with:
          docs-dir: docs
          extra-packages: mkdocs-material
