name: "Deploy docs to GitHub Pages"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: atirut-w/mkdocs-deploy@master
        with:
          extra-packages: mkdocs-material
